---

name: ci

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  test:
    name: test (${{ matrix.ruby.name }}, ${{ matrix.deps }})
    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    strategy:
      fail-fast: false

      matrix:
        ruby: [{ name: 3.0, value: 3.0.3 }]

        os: [ubuntu-20.04]

        deps: [rails_70]

    env:
      COVERAGE: true

    steps:
      - uses: actions/checkout@v2

      - name: Configure bundler (default)
        run: |
          echo "BUNDLE_GEMFILE=Gemfile" >> $GITHUB_ENV
          echo "BUNDLE_PATH=$(pwd)/vendor/bundle" >> $GITHUB_ENV

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby.value }}
          bundler-cache: true

      - name: Setup git
        run: |
          git config --global user.email activeadmin@ci.dummy
          git config --global user.name ActiveAdmin

      - name: Create test app
        run: bin/rake
